version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.3
    container_name: "es"
    ports:
      - 9200:9200
    environment:
      discovery.type: 'single-node'
      xpack.security.enabled: 'false'
      xpack.security.transport.ssl.enabled: 'false'
      # ELASTIC_PASSWORD: 'secret'
      # ES_JAVA_OPTS: -Xm1g -Xms1g
    volumes:
      - es_data:/usr/share/elasticsearch/data

volumes:
  es_data: